version: '3.1'

services:
  tronscan:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "9001:9000"
    environment:
      NODE_FULL_IP: "43.198.147.230"
      NODE_FULL_PORT: "50051"
      NODE_SOLIDITY_IP: "43.198.147.230"
      NODE_SOLIDITY_PORT: "50051"
      ENABLE_SYNC: "true"
      ENABLE_NETWORK_SCANNER: "true"
      SECRET_KEY: "aSLtAkzrIY9pTPyboOih"

  redis:
    image: redis:4.0
    volumes:
      - /tronscan/redis:/data
  pgsql:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tronscan
      POSTGRES_USER: postgres
    volumes:
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - /tronscan/postgresql:/var/lib/postgresql/data
